feat(ui): add DeviceControlCard component
VKCOM/devicehub pull request #41
Opened 2024-12-04 08:57 UTC by oshcherbakovv

2024-12-04 08:59 UTC, oshcherbakovv commented
<img width="1792" alt="image" src="https://github.com/user-attachments/assets/86a65e89-909c-40e6-a6a3-de5d6cbc89d8">

2024-12-04 09:06 UTC, irdkwmnsb requested changes

2024-12-04 09:06 UTC, irdkwmnsb commented on ui/src/components/ui/device-control-panel/device-control-card/device-control-card.tsx
> +  icon?: DeviceControlCardIcon
Maybe make this `after` and allow for arbitrary content and not just icons?
And pass icons as DeviceControlCardIcon in both `after` and `before`?

2024-12-05 13:55 UTC, irdkwmnsb approved these changes

2024-12-05 14:00 UTC, merged